# This is a basic workflow to help you get started with Actions

name: data4

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
     - uses: azure/actions/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - uses: azure/postgresql@v1
       with:
         connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
         server-name: dss-postgresql-server
         plsql-file: './data4.sql'    
     - uses: actions/checkout@v1
     - uses: azure/actions/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - uses: azure/postgresql@v1
       with:
         connection-string: ${{ secrets.AZURE_POSTGRESQL_CONNECTION_STRING }}
         server-name: dss-postgresql-server
         plsql-file: './data5.sql'
       
